{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  {{- if .Values.ingress.tls }}
  annotations:
    kubernetes.io/tls-acme: "true"
  {{- end }}
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  rules:
  - host: {{ .Release.Name }}.{{ .Values.basedomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.service.externalPort }}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Release.Name }}.{{ .Values.basedomain }}
    secretName: {{ .Release.Name }}-tls
  {{- end -}}
{{- end -}}
